# -*- coding: utf-8 -*-
"""Fácil de 10. Clustering II .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0ni8j2le7zx87G6JPXbK-DNZRTg8CN2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""El dataset con el que vamos a trabajar contiene datos de los valores nutricionales de distintos cereales comerciales, vamos a comprobar como se parecen entre sí.

[Enlace al dataset](https://drive.google.com/file/d/1idn75gVVrFEWSNhaLooM66YEOm3hmYKP/view?usp=share_link)

importa el dataset en la siguiente celda en la variable cereals
"""

cereals = pd.read_csv('/content/cereal.csv',sep=';', header = 0)

cereals.head()

cereals= cereals.drop('Unnamed: 12',axis=1)

cereals.head()

#@title Comprueba la creación del dataframe
def check():
  if str(cereals.tail())=="                   name  calories  protein  fat  sodium  fiber  carbo  sugars  \\\n72              Triples     110.0      2.0  1.0   250.0    0.0   21.0     3.0   \n73                 Trix     110.0      1.0  1.0   140.0    0.0   13.0    12.0   \n74           Wheat Chex     100.0      3.0  1.0   230.0    3.0   17.0     3.0   \n75             Wheaties     100.0      3.0  1.0   200.0    3.0   17.0     3.0   \n76  Wheaties Honey Gold     110.0      2.0  1.0   200.0    1.0   16.0     8.0   \n\n    potass  vitamins  weight  cups  \n72    60.0      25.0     1.0  0.75  \n73    25.0      25.0     1.0  1.00  \n74   115.0      25.0     1.0  0.67  \n75   110.0      25.0     1.0  1.00  \n76    60.0      25.0     1.0  0.75  ":
    return 'Creación correcta'
  else:
    return 'Incorrecto, comprueba el datafame'
check()

"""Comprueba cuantas filas tiene el dataset"""

cereals.shape

"""Comprueba los 5 primeros elementos del dataframe."""

cereals.head()

cereals.nunique()

"""Comprueba cuantos missing values tiene cada columna"""

cereals.isna().sum()

"""Elimina las filas con missing values"""

cereals = cereals.dropna()

"""#Ejercicio 1 dendograma

Realiza el dendograma para agrupar los cereales en función de su valor nutricional.
"""

import scipy.cluster.hierarchy as sch

X = cereals.iloc[:, 1:].values

dendograma = sch.dendrogram(sch.linkage(X, method = 'ward'))
plt.title('Dendograma')
plt.xlabel('Cereales')
plt.ylabel('Distancia Euclidiana')
plt.show()

"""¿Cuantos grupos diferentes se obserban en el dendograma? Almacena la respuesta como número entero en la variable res1"""

res1=3

"""#Ejercicio 2 Clustering Aglomerativo

Vamos a crear el modelo de clusterring aglomerativo de sklearn con n_clusters igual al observado en el dendograma.
"""

# Importamos el algoritmo de sklearn
from sklearn.cluster import AgglomerativeClustering

ac = AgglomerativeClustering(n_clusters = 3, metric = 'euclidean', linkage = 'ward')
y_hc = ac.fit_predict(X)

#Visualizar los clusters
plt.scatter(X[y_hc == 0, 0], X[y_hc == 0, 1], s = 100, c = 'red', label = 'Cluster 1')
plt.scatter(X[y_hc == 1, 0], X[y_hc == 1, 1], s = 100, c = 'blue', label = 'Cluster 2')
plt.scatter(X[y_hc == 2, 0], X[y_hc == 2, 1], s = 100, c = 'green', label = 'Cluster 3')
#plt.scatter(X[y_hc == 3, 0], X[y_hc == 3, 1], s = 100, c = 'cyan', label = 'Cluster 4')
#plt.scatter(X[y_hc == 4, 0], X[y_hc == 4, 1], s = 100, c = 'magenta', label = 'Cluster 5')
plt.title('Clusters of cereals')
plt.xlabel('Calories')
plt.ylabel('Protein')
plt.legend()
plt.show()

"""#Ejercicio 3 Algoritmo K-means

En esta ocasión en lugar de utilizar el dendograma realizaremos el clustering mediante K-means
"""

from sklearn.cluster import KMeans

wcss=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',max_iter=300,n_init=10,random_state=0)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,11),wcss)
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

"""¿Cuál es el número óptimo de clusters según el metodo del codo?"""

res4=4

"""Realiza la predicción mediante k-means con el número de clusters óptimos según el método del codo."""

kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(X)
y_kmeans = kmeans.predict(X)

fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(15, 5))
ax1.scatter(X[y_hc == 0, 0], X[y_hc == 0, 1], s = 100, c = 'red', label = 'Cluster 1')
ax2.scatter(X[y_hc == 1, 0], X[y_hc == 1, 1], s = 100, c = 'blue', label = 'Cluster 2')
ax3.scatter(X[y_hc == 2, 0], X[y_hc == 2, 1], s = 100, c = 'green', label = 'Cluster 3')
ax1.set_title('Clusters of cereals')
ax2.set_title('Clusters of cereals')
ax3.set_title('Clusters of cereals')
ax1.set_xlabel('Calories')
ax2.set_xlabel('Calories')
ax3.set_xlabel('Calories')
ax1.set_ylabel('Protein')
ax2.set_ylabel('Protein')
ax3.set_ylabel('Protein')
ax1.legend()
ax2.legend()
ax3.legend()
plt.show()

#@title Consigue el Token para corregir el ejercicio en Nodd3r
import hashlib

correct = str(res1)+str(y_hc) +str(y_kmeans)
pwd = hashlib.sha256(str(correct).encode())
print('El token para corregir en Nodd3r es:\n',pwd.hexdigest())